"""create_availability_rules

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 15:25:24.014657

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stylist_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("working", "break", "day_off", name="rulekind"),
            nullable=False,
        ),
        sa.Column("weekday", sa.SmallInteger(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("off_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'day_off' AND off_date IS NOT NULL AND weekday IS NULL AND start_time IS NULL AND end_time IS NULL) OR (kind IN ('working', 'break') AND off_date IS NULL AND weekday IS NOT NULL AND start_time IS NOT NULL AND end_time IS NOT NULL)",
            name="ck_availability_rules_shape_matches_kind",
        ),
        sa.CheckConstraint(
            "start_time IS NULL OR end_time > start_time",
            name="ck_availability_rules_end_after_start",
        ),
        sa.CheckConstraint(
            "weekday IS NULL OR weekday BETWEEN 0 AND 6",
            name="ck_availability_rules_weekday_range",
        ),
        sa.ForeignKeyConstraint(["stylist_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_availability_rules_stylist_id_weekday",
        "availability_rules",
        ["stylist_id", "weekday"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_availability_rules_stylist_id_weekday", table_name="availability_rules"
    )
    op.drop_table("availability_rules")
    # drop_table leaves the enum type behind; a later upgrade would fail without this.
    sa.Enum(name="rulekind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
