"""add_unique_day_off_index_to_availability_rules

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 15:57:46.836569

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_availability_rules_stylist_id_off_date",
        "availability_rules",
        ["stylist_id", "off_date"],
        unique=True,
        postgresql_where=sa.text("kind = 'day_off'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_availability_rules_stylist_id_off_date",
        table_name="availability_rules",
        postgresql_where=sa.text("kind = 'day_off'"),
    )
    # ### end Alembic commands ###
